### ISSUE TITLE
Kiosk Mode für andere Nutzer

### ISSUE THREAD

**Issue by swa72** [swa72/home-assistant#105]
# Intro

we do not create a new dashboard for the user
we create one view for the user in the default dashboard
we use kioskmode to disable the user from doing anything else

# TODO

- install kioskmode (don't forget to add resources)
- create user, e.g. "mieter", allow to login, not admin
- to avoid that the user may switch to other dashboards (changing the URL and stuff)
  - for all other dashboards X do
    - for all other views in X remove mieter in "visibility"
- Edit your default dashboard , create a view "mieter" and add elements/entities to your liking e.g.
```
type: entities
entities:
  - entity: sensor.watermain_value
    name: Wasserzähler
  - entity: sensor.gasverbrauch
  - entity: sensor.smlreadercounter
    name: Stomzähler
title: Zähler
```
- Then edit YOUR default dashboard and click ... top right and "Raw config editor"
- Add to the top, right before "views":
```
kiosk_mode:
  user_settings:
    - users:
        - "mieter"
      hide_sidebar: true
      hide_header: true
views:
```
- Disable visibility in view "mieter" for all other users
- Last but not least: remove all users other than "mieter" from all other views you have in your default dashboard
