### ISSUE TITLE
show open doors only if one is open

### ISSUE THREAD

**Issue by swa72** [swa72/home-assistant#39]

**Comment by swa72** [comment]
```
type: conditional
conditions:
  - entity: group.oeffnungen
    state: 'on'
card:
  type: custom:auto-entities
  card:
    type: glance
    show_icon: false
    show_state: false
  filter:
    include:
      - entity_id: binary_sensor.*tur
        state: 'on'
      - entity_id: binary_sensor.fenster*
        state: 'on'
  exclude: null
```
