### ISSUE TITLE
Document Spotify on Echo dot; create UI with list of favorite playlists

### ISSUE THREAD

**Issue by swa72** [swa72/home-assistant#66]

**Comment by swa72** [comment]
that does the trick for me 
```yaml
alias: Spotify background jazz
sequence:
  - service: media_player.play_media
    target:
      entity_id: media_player.spotify_swa72
    data:
      media_content_id: >-
        https://open.spotify.com/playlist/37i9dQZF1DXaIrEwuQ3hyy?si=887717bbbc1f46e9
      media_content_type: playlist
  - service: media_player.shuffle_set
    target:
      entity_id: media_player.spotify_swa72
    data:
      shuffle: true
  - service: media_player.media_next_track
    data:
      entity_id: media_player.spotify_swa72
mode: single
```
