### ISSUE TITLE
Motion detection and doorbell notify but without attachment :-/

### ISSUE THREAD

**Issue by swa72** [swa72/home-assistant#68]

**Comment by swa72** [comment]
works with 
```yaml
service: notify.mobile_app_iphone
data:
  data: 
    ttl: 0
    priority: high
    image: "http://192.168.178.83:8123/local/tmp/snapshot_garagecam.jpg"
  message: foo
```
