### ISSUE TITLE
best practise logging

### ISSUE THREAD

**Issue by swa72** [swa72/home-assistant#73]
to debug an automation or script add to lovelace 
```yaml
type: logbook
entities:
  - automation.fake_test_automation
hours_to_show: 12
```
In the automation use
```yaml
  - service: logbook.log
    data:
      entity_id: automation.fake_test_automation
      message: some message
      name: automation.fake_test_automation
```
You could also run the trace function.
