### ISSUE TITLE
SQL Sensor

### ISSUE THREAD

**Issue by swa72** [swa72/home-assistant#75]
find the sensor , see https://community.home-assistant.io/t/how-to-fix-statistics-data-e-g-energy-data/360966
then pick the latest entry
````sql
SELECT `sum` FROM `statistics` WHERE `metadata_id`= 103 ORDER BY `id` DESC LIMIT 1

**Comment by swa72** [comment]
debug me in a VM, need to restart :-/ "reloading template entities" doesn't do it.

**Comment by swa72** [comment]
```yaml
- platform: sql
  db_url: !secret db_url
  queries:
    - name: Entfeuchter Grand Total
      query: "SELECT * FROM statistics WHERE metadata_id=103 ORDER BY id DESC LIMIT 1;"
      column: "sum"
      unit_of_measurement: kWh 
```
