### ISSUE TITLE
Delay gets cancelled when changing automations in UI or HA restarts :-/

### ISSUE THREAD

**Issue by swa72** [swa72/home-assistant#8]

**Comment by swa72** [comment]
```
alias: test turn off after n minutes
description: ''
trigger:
  - platform: state
    entity_id: input_boolean.swatrigger
    from: 'off'
    to: 'on'
  - platform: time
    at: input_datetime.swadatetime
  - platform: homeassistant
    event: start
action:
  - variables:
      swaobject: input_boolean.swaswitch
      is_on: '{{ is_state(swaobject, ''on'') }}'
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.platform == ''state'' and not is_on }}'
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: '{{ swaobject }}'
          - service: input_datetime.set_datetime
            target:
              entity_id: input_datetime.swadatetime
            data:
              timestamp: '{{ (now() + timedelta(minutes=5)).timestamp()| int(0)  }}'
      - conditions:
          - condition: template
            value_template: '{{ trigger.platform == ''state'' and is_on }}'
        sequence:
          - service: input_datetime.set_datetime
            target:
              entity_id: input_datetime.swadatetime
            data:
              timestamp: '{{ (now() + timedelta(minutes=5)).timestamp()| int(0)  }}'
      - conditions:
          - condition: template
            value_template: >-
              {{ (trigger.platform == 'time' or trigger.platform ==
              'homeassistant' ) and is_on }}
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: '{{ swaobject }}'
mode: single
```
